### ISSUE TITLE
Adicionar o segundo governo Passos Coelho

### ISSUE THREAD

**Issue by rlafuente** [centraldedados/governos#1]
Fontes:
- lista de [ministros](http://www.portugal.gov.pt/pt/o-governo/ministros.aspx) e [secretários de estado](http://www.portugal.gov.pt/pt/o-governo/secretarios-de-estado.aspx)

Se o site mudar depois da tomada de posse do governo Costa, estes conteúdos devem estar disponíveis no arquivo histórico do site do governo.

**Comment by rlafuente** [comment]
Atualizei as entradas do 19º Governo, mas ainda faltam o 2º governo Passos Coelho e o atual governo Costa. A Wikipedia tem as melhores listas:
- [XX Governo](https://pt.wikipedia.org/wiki/XX_Governo_Constitucional_de_Portugal)
- [XXI Governo](https://pt.wikipedia.org/wiki/XXI_Governo_Constitucional_de_Portugal)

**Comment by aiscarvalho** [comment]
Está feito. Agora falta atualizar o datapackage.json, vou criar uma issue para isso.
